### PR TITLE
Some updates for TestCircuitORAMRec{,Server,Client}

### PR DESCRIPTION
**Pull request by weikengchen**
This PR consists of the following changes:

- remove the false alarm of inconsistency in TestCircuitOramRec.java, which is now commented.
- add 1s delay for RecClient after one experiment. for remote testing (my experiment environment has 20ms latency), RecClient starts too early that RecServer is not prepared, and TLS reset.
- remove the strange comment in RecServer.

### CODE REVIEW

**Comment by weikengchen** [comment]
I am working on an evaluation (and comparison) with existing ORAMs.

I tested on both FlexSC's CircuitORAM and floram's CircuitORAM (or sqrtOram's CircuitORAM).

Because FlexSC seems to be the only version that the storage is "Online OT".

floram/sqrtOram "Offline OT" the whole ORAM will lead to high memory demand and a storage overhead of the security parameter. 

But therefore, FlexSC needs more time for online OT. 

I feel this is difficult to argue which one is better. 

Some of my experiments show "Offline OT" circuit ORAM is better than FLORAM for small block sizes because FLORAM has to use many online OTs.

**Comment by weikengchen** [comment]
and wish you good luck with your faculty interview in Gatech!

**Comment by wangxiao1254** [comment]
Thanks. But please be noted that the implementation is in JAVA without
hardware AES acceleration . So the performance does not reflect the best
possible.

**Comment by weikengchen** [comment]
This would be a noticeable point. Will add to the discussion. 

Correct me if I am wrong:
So, Circuit ORAM (online OT version) has been implemented in FlexSC and ObliVM. They seem to be not AES-NI.

Circuit ORAM (offline OT version, or sqrtOram's version, later used by FLORAM) are based on Obliv-C with AES-NI.

So, there is no existing platform in the middle, to show how online OT & offline OT trade-offs in the demand for storage space and the online latency (and possible the initialization time)?

**Comment by weikengchen** [comment]
By Offline OT, I mean we turn every bits of the ORAM into labels beforehand.

By Online OT, I mean storing the block in secret shares, and turning them into labels when we `prepare the path`

**Comment by wangxiao1254** [comment]
Yes to the first q.

I think offline OT has its specific meaning in MPC, so not sure if it is a
good name :)

**Comment by weikengchen** [comment]
Yes. Maybe I should not name it. Just say in details.

**Comment by weikengchen** [comment]
New change automatically goes here by Github.

They are for the issue #3

**Pull request merged**
